import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { getExtraPages } from "@/sanity/sanity-utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sanity Boilerplate",
  description: "Generated by Nadya Corscadden",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const extraPages = await getExtraPages();
  return (
    <html lang="en">
      <body className={`my-10 ${inter.className}`}>
        <header>
          <div className="flex flex-row justify-between">
            <div>
              <Link
                href="/"
                className="p-3 m-5 rounded not-italic my-10 text-xl font-bold bg-gradient-to-r from-emerald-950 to-emerald-800 bg-clip-text text-transparent drop-shadow-2xl transition-all hover:bg-gradient-to-l hover:from-pink-500 hover:via-purple-700 hover:to-pink-500 border-2 border-transparent hover:border-purple-700"
              >
                HOME
              </Link>
            </div>
            <div className="pr-5">
              <Link
                href="/about"
                className="mx-3 not-italic text-emerald-800 no-underline hover:bg-emerald-900 hover:text-white p-3 transition-all rounded"
              >
                About
              </Link>
              <Link
                href="/media"
                className="mx-3 not-italic text-emerald-800 no-underline hover:bg-emerald-900 hover:text-white p-3 transition-all rounded"
              >
                Media
              </Link>
              <Link
                href="/gallery"
                className="mx-3 not-italic text-emerald-800 no-underline hover:bg-emerald-900 hover:text-white p-3 transition-all rounded"
              >
                Gallery
              </Link>
              {extraPages.map((page) => (
                <Link
                  key={page._id}
                  href={`/${page.slug}`}
                  className="mx-3 not-italic text-emerald-800 no-underline hover:bg-emerald-900 hover:text-white p-3 transition-all rounded"
                >
                  {page.name}
                </Link>
              ))}
              <Link
                href="/contact"
                className="mx-3 not-italic text-emerald-800 no-underline hover:bg-emerald-900 hover:text-white p-3 transition-all rounded"
              >
                Contact
              </Link>
            </div>
          </div>
        </header>
        <main className="py-10 max-w-7xl mx-auto px-5">{children}</main>
      </body>
    </html>
  );
}
