import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sanity Boilerplate",
  description: "Generated by Nadya Corscadden",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`my-10 ${inter.className}`}>
        <header>
          <Link
            href="/"
            className="p-3 m-5 rounded not-italic my-10 text-xl font-bold bg-gradient-to-r from-emerald-950 to-emerald-800 bg-clip-text text-transparent drop-shadow-2xl transition-all hover:bg-gradient-to-l hover:from-pink-500 hover:via-purple-700 hover:to-pink-500 border-2 border-transparent hover:border-purple-700"
          >
            HOME
          </Link>
        </header>
        <main className="py-10">{children}</main>
      </body>
    </html>
  );
}
